name: Run postman collection
on:
  push:
    branches: 'main'
jobs:
  postman-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g minimist
          npm install -g newman-reporter-ctrf-json
          npm install -g @actions/core

      - name: Run Postman Collection
        working-directory: ./
        run: |
          NODE_PATH=$(npm root -g) node run-collections.js -e ./environments/dev.json
      - name: Publish Test Reports Postman Collection
        working-directory: ./
        run: |
          NODE_PATH=$(npm root -g) npx github-actions-ctrf api-reports/api_report_ctrf.json    
